### ISSUE TITLE
Change the default UDP port for ADS-B data

### ISSUE THREAD

**Issue by n251ea** [apps4av/avare#436]
Change the default UDP port from 43211 to 4000 since 4000 appears to be default port for all ADS-B in devices to send their telemetry on.

**Comment by avcomware** [comment]
Hi.I think that every new compile and or change is likely to cause backwards compatibility and No changes should be made unless strictly necessary. 
I do not think that this will help, the users already know how to set things up and this is a very superficial and unnecessary.TV

    On Monday, January 17, 2022, 07:15:01 AM PST, n251ea ***@***.***> wrote:  
 
 


Change the default UDP port from 43211 to 4000 since 4000 appears to be default port for all ADS-B in devices to send their telemetry on.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
